version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --requirepass pass

volumes:
  mongo-data:
  redis-data:
